### ISSUE TITLE
meshchain部署不成功

### ISSUE THREAD

**Issue by tinglany** [FISCO-BCOS/meshchain#1]
meshchain的README文档中：
1. cd tool
2. vim config.json，替换 var proxy="http://ip:port"为路由链中某个节点的ip和rpc端口，保存
3. babel-node deploy.js Meshchain (注意没有.sol结尾)
4. 首次添加Meshchain合约，执行babel-node abi_name_service_tool.js add Meshchain；否则执行babel-node abi_name_service_tool.js update Meshchain
5. 检查是否添加成功，执行babel-node abi_name_service_tool.js list，如果输入的结果中，包含有Meshchain，则代表成功

**遇到的问题：**
“热点链，用户链也执行以上的步骤” 是执行哪几个步骤？我在node0上执行步骤1~5，在node1上 执行1~5步的第4步一直过不去，我用babel-node abi_name_service_tool.js update Meshchain 这条命令总是提示“====> Are you sure you want cover it?(Y)”；
用add 又提示“add failed , ====> contract => Meshchain version =>  is already exist. If you need ,please cover it or update its version!!!”

在文档中未找到其他相关介绍资料，请问该如何解决？

**Comment by fisco-dev** [comment]
是四条独立的链，而不是一条链的四个节点。更方便的体验，请参考一键部署
