### ISSUE TITLE
一键部署脚本问题

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/meshchain#7]
在脚本中kill node和start node中间最好加入sleep延时，否则在处理速度慢的主机上启动节点经常遇到如下fail

![tim 20180515101134](https://user-images.githubusercontent.com/25951395/40032849-63e922b2-5828-11e8-9613-ca1729a75da2.png)

**Comment by iamyh** [comment]
ok.这个版本已经解决这个问题。谢谢
